### ISSUE TITLE
TSV with line breaks not supported

### ISSUE THREAD

**Issue by shane-smith** [mechatroner/vscode_rainbow_csv#10]
Issue Type: <b>Bug</b>

If one of the columns contains line breaks (and is surrounded in quotes), Rainbow CSV does not detect this correctly and treats the line breaks as a new record.

For example, take a record like this:

    This is column 1 <tab> "This is
    the second
    column here" <tab> This is column 3 <tab> This is column 4

Highlighting is as follows:
- "This is column 1" uses correct colour
- "the second" and "column here" appear same as above, but they are actually part of the second column.
- "This is column 3" uses column 2 highlighting
- "This is column 4" uses column 3 highlighting

Extension version: 0.4.1
VS Code version: Code 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288, 2018-06-13T17:41:50.128Z)
OS version: Darwin x64 17.5.0

**Comment by mechatroner** [comment]
Hello @shane-smith !
There are multiple sides of this problem. 
1. Most common definition of TSV is that TSV files can't contain tabs or newlines inside fields, unlike most common definition of CSV. Here is definition from IANA: https://www.iana.org/assignments/media-types/text/tab-separated-values

2. It is technically not possible currently to support newlines inside fields. See discussion here #4 Although it is technically possible to support tabs inside double quoted fields, and such grammar can be added later.

**Comment by shane-smith** [comment]
Thanks for the quick response.

I'm disappointed to hear that it's not possible to support new lines, but I understand that's not something you have control over.

The reason I need this is for the Manager.io accounting system. All imports/exports are tab delimited, and batch updates are essentially an export-then-import process. I was hoping to edit the TSV using the extension... but any records that include an address (e.g. Customers) result in the multi-line issue.

I'll try from the other end and see if the developer of Manager is able to make the export format more consistent with the IANA definition ... or offer a CSV alternative.

Thanks again.

**Comment by shane-smith** [comment]
Hmm. Just reading that definition:

> Each record must have the same number of fields.

I'm not sure what the technical restriction is (skimmed over the related issue, but I'll need to read it in more depth later when back in office)... but would this logic work?

1. Read in first line to the first line break. We now know how many columns there should be per line.
2. When processing the rest of the file, ignore *all* line breaks (even those that separate two records) and separate records based on column count instead.

If there are 5 headers... every 5 tabs is a new record.

You may have already considered such a possibility. Either way, this looks to be a duplicate of #4 so I'll close it.

**Comment by shane-smith** [comment]
Will close this as it looks to be a duplicate of the #4 that you linked.
