### ISSUE TITLE
Add vscode.dev support

### ISSUE THREAD

**Issue by StevenH237** [mechatroner/vscode_rainbow_csv#100]
Rainbow CSV is not supported in VSCode for the web, but it seems like at least most of the features (maybe not RBQL?) would work if it were ported. It would be nice to see.

A guide to porting extensions can be found [here](https://code.visualstudio.com/api/extension-guides/web-extensions).

**Comment by mechatroner** [comment]
I am actually already working on porting the extension in this branch: https://github.com/mechatroner/vscode_rainbow_csv/tree/webpack
The main functionality worked with some minimal changes, and now I am trying to enable JS-based RBQL.
Maybe I should release an MVP first and then add additional functionality, IDK.
Anyway thanks for creating this ticket, I will post updates here.

**Comment by mechatroner** [comment]
So, I just published an MVP without RBQL support, but the main features should work. Please give it a try and let me know if you find any issues. I'll keep this ticket open until I migrate js-based RBQL.

**Comment by StevenH237** [comment]
I installed the extension in vscd and this popped up right away:
![image](https://user-images.githubusercontent.com/1627071/147376250-7988b693-07e5-48ed-acf0-15495d4c01b0.png)

That being said, the basic functionality seems to be working fine (#4 notwithstanding).

**Comment by mechatroner** [comment]
@StevenH237 did you get the error when you installed the extension in the regular vscode or at vscode.dev? I just updated it to 2.0.0 in the regular vscode and I don't have the error.

**Comment by StevenH237** [comment]
I got it on vscode.dev.

**Comment by mechatroner** [comment]
Got it, thanks! I will play a little to try and reproduce this.

**Comment by mechatroner** [comment]
I forgot to close the ticket, the extension has been working on vscode.dev for quite some time now.
