### ISSUE TITLE
Add configuration to customize output_path

### ISSUE THREAD

**Issue by TheRealChssAddct** [mechatroner/vscode_rainbow_csv#101]
The output_path is always tmp_dir and the constructed output_file_name

```
let tmp_dir = os.tmpdir();
let output_file_name = get_dst_table_name(input_path, output_delim);
let output_path = path.join(tmp_dir, output_file_name);
```
I would like the ability to customize this with the following new configuration settings

1) a setting to allow me to choose the output dir.  Perhaps something like this:

```
"rainbow_csv.output_dir": {
  "type": "string",
  "default": "tmpDir",
  "description": "the output directory of the results file",
  "enum": [
      "tmpDir",
      "inputDir"
  ],
  "enumDescriptions": [
      "output file will be in the tmpdir of the operating system",
      "output file will be in same directory of the input file"
  ]
},
```
tmpdir is default and keeps current behavior

2) a setting to customize the output name.
Currently, if my source file is blah.csv, then the output filename is blah.csv.csv. blech.
Perhaps a setting like:

```
"rainbow_csv.output_filename_template": {
    "type": "string",
    "default": "",
    "description": "Optional output file name template. Use {basename} for the filename without extension, and {extname} for the extension. Eg., rbql-{basename}-results.{extname} would change blah.csv to rbql-blah-results.csv "
}
```
I'd be happy to do a PR for these changes.

**Comment by TheRealChssAddct** [comment]
My implementation would be something close to te following:

### In package.json:

Add the two configuration contributions from the issue above.

### In extension.js:

1) Change line 835 from 
`let tmp_dir = os.tmpdir();`
to 
`let tmp_dir = get_tmpdir(input_path);`

2) Add this function:
```
function get_tmpdir(input_path) {
    let tmpdir = os.tmpdir();

    const config = vscode.workspace.getConfiguration('rainbow_csv');
    if (config && config.get('output_dir') === 'inputDir')
        tmpdir = path.dirname(input_path);

    return tmpdir;
}
```

3) Change function get_dst_table_name to be this:
```
function get_dst_table_name(input_path, output_delim) {
    var table_name = path.basename(input_path);
    var orig_extension = path.extname(table_name);
    var extensionless_table_name = path.basename(input_path, orig_extension);
    var delim_ext_map = {'\t': '.tsv', ',': '.csv'};
    var dst_extension = '.txt';
    if (delim_ext_map.hasOwnProperty(output_delim)) {
        dst_extension = delim_ext_map[output_delim];
    } else if (orig_extension.length > 1) {
        dst_extension = orig_extension;
    }

    let dst_table_name = table_name + dst_extension;

    const config = vscode.workspace.getConfiguration('rainbow_csv');
    let output_filename_template = config ? config.get('output_filename_template') : '';
    if (output_filename_template) {
        var output_filename = output_filename_template
            .replace('{basename}', extensionless_table_name)
            .replace('{extname}', orig_extension);
        dst_table_name = output_filename + dst_extension;
    }

    return dst_table_name;
}
```

**Comment by mechatroner** [comment]
Thanks for opening the issue, I like this idea!

I am currently working on web version (for vscode.dev) in the webpack branch, but once I merge these changes into master I will apply your patch with some minor modifications, e.g. I would probably prefer to use `$TMPDIR` and `$INPUTDIR` as placeholders for tmp and input directories and I would also make it possible to specify any other custom absolute path there.

An option to provide a custom basename template also seems to be very reasonable, I will add this too.

If you want, you can make an actual PR, but if not, I will handle this myself, it could be a little tricky to properly set up the dev environment for an extension, and for me, this change is really very easy and quick to do. But if you want to practice - feel free to go ahead with the PR, there are some instructions at the top of extension.js about how to run the thing in dev mode, and I might still somewhat adjust your code after it is submitted, so no promises here :smiley:

**Comment by mechatroner** [comment]
Done. Version 2.1.0 supports output path configuration as we discussed.
