### ISSUE TITLE
Open-VSX publish out of date

### ISSUE THREAD

**Issue by Chrismettal** [mechatroner/vscode_rainbow_csv#102]
While Rainbow CSV is on version `2.0.0` on the Visual Studio Marketplace, it is only at version `1.7.1` on the Open-VSX Marketplace, used by VSCodium and Code-server for example.

It is possible to have Github Actions automatically publish your extension to both marketplaces as soon as you tag a release so you don't have to do it yourself twice. You can find a working example workflow [here](https://github.com/Chrismettal/Behave-full-Theme/blob/master/.github/workflows/publish.yml) using [HaaLeo's action](https://github.com/HaaLeo/publish-vscode-extension).

**Comment by mechatroner** [comment]
Thanks, I just updated the extension in open-vsx. 
The idea to publish the extension using a GitHub action sounds very interesting, but I personally don't really believe in this approach - IMO the effort to develop and maintain such action for me is much higher than to manually run the command (after all I need to launch vscodium and try the new version each time I do this anyway). I will try to re-publish the extension to open-vsx each time when I do a significant change or bug fix.

**Comment by Chrismettal** [comment]
That is the beauty of CI/CD, no need to maintain it once it's set up! And HaaLeo made setting his action up super easy. 

Thank you for updating so quickly!
