### ISSUE TITLE
Coloring doesn't work properly

### ISSUE THREAD

**Issue by kanlukasz** [mechatroner/vscode_rainbow_csv#105]
From what I can see the coloring is not working properly

### Screenshot:
![image](https://user-images.githubusercontent.com/30685349/150480534-875309d4-502f-4ecc-9635-5afac090b882.png)

### Delimiter used in the CSV file:
`;`

### CSV to test:
```
SYMBOL;NAME;EAN;CENAHURT;CENADETAL;WEIGHT;OBJ;SYMBOL;NAME;EAN;CENAHURT;CENADETAL;WEIGHT;OBJ;SYMBOL;NAME;EAN;CENAHURT;CENADETAL;WEIGHT;OBJ
1102;toaletka1102antycz;5901477200014;5;6;9;<imgsrc="https://server.com/sssss.jpg">;1102;toaletka1102antycz;5901477200014;5;6;9;<imgsrc="https://server.com/sssss.jpg">;1102;toaletka1102antycz;5901477200014;5;6;9;<imgsrc="https://server.com/sssss.jpg">
1102bb;toaletka1102biało-biała;5901477231186;540,35;6;663,33;66;1102bb;toaletka1102biało-biała;5901477231186;540,35;6;663,33;66;1102bb;toaletka1102biało-biała;5901477231186;540,35;6;663,33;66
acoma160szd;łóżkoacoma160x200kolorszary/dąbt.ap;69,6;5;jjj;5;6;acoma160szd;łóżkoacoma160x200kolorszary/dąbt.ap;69,6;5;jjj;5;6;acoma160szd;łóżkoacoma160x200kolorszary/dąbt.ap;69,6;5;jjj;5;6
```

### Tested in the environment:
```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

**Comment by kanlukasz** [comment]
Oh, looks like string delimiters needs to be used too.
Can we get around this somehow?
I have a large database where string delimiters for `"` or `>` are not included

**Comment by mechatroner** [comment]
Looks like you just need to switch filetype to `CSV (semicolon)` or select the semicolon character -> right click -> Set as Rainbow Separator.

> looks like string delimiters needs to be used too.

Do you mean that `"` have no special meaning in your case? Yeah, this is one of the current limitations, there is only one csv dialect with string escape characters. I could create another dialect and name it e.g. `csv simple` but this might add some confusion by being present in the filetype list, unlike some other editors VSCode currently doesn't support dynamic syntax generation. 
BTW there is also `csv (pipe)` dialect which doesn't put special meaning into `"` characters so you can theoretically replace all commas with `|` character and switch the filetype to `csv (pipe)`

**Comment by kanlukasz** [comment]
> Looks like you just need to switch filetype to `CSV (semicolon)` or select the semicolon character -> right click -> Set as Rainbow Separator.

Yes you are right. Everything works fine after using this option 👍 


> Do you mean that `"` have no special meaning in your case? 

I mean (for example) i can't use `Align` option because it gets an error:
![image](https://user-images.githubusercontent.com/30685349/150651540-304bd3d3-211f-4cef-8457-15b0409ee2f3.png)
Is this the limitation you mentioned?

**Comment by mechatroner** [comment]
Yeah, basically to handle your use case there should be a "non-standard" semicolon dialect, but it is not viable to add it right now, unfortunately. As I mentioned you can try to replace `;` with `|` or TAB and switch the dialect to `csv (pipe)` or `TSV`. Another option is to replace all double quotes with e.g. single quotes or double single quotes: `"` -> `''`, this would also allow you to align the file.
And BTW having `<` in the file is not a problem since all CSV dialects that I am aware of do not handle this character in any special way.
The general solution to this problem is dynamic syntax generation which is also discussed in #1

**Comment by kanlukasz** [comment]
I cannot change the structure as this file will be imported into another application later.
Thanks for the clarification anyway
