### ISSUE TITLE
Context menu pollution: "preview big csv: head"

### ISSUE THREAD

**Issue by FreHu** [mechatroner/vscode_rainbow_csv#107]
The extension adds this command to all right click menus in the file explorer, which is unnecessary. Could it please be changed to only show up for csv? There is also a contribution for `Preview big csv: tail` but for some reason this one does not appear in the menu for me.

**Comment by mechatroner** [comment]
It's actually possible to disable it in the settings (and enable the tail command). But I agree with you that current defaults are not perfect, I will try to think if it is possible to have a better balance between aesthetics and feature discovery.

**Comment by ManuelHentschel** [comment]
Adding `resourceLangId =~ /^[ct]sv/` to the corresponding [when clause](https://github.com/mechatroner/vscode_rainbow_csv/blob/b8792ae8e6bee5dfaaee91ac7975ba52cac18b3b/package.json#L140) seems to fix this issue for non-csv files.

**Comment by mechatroner** [comment]
Thank you @ManuelHentschel, this sounds like a great compromise solution, I will implement the change.

**Comment by mechatroner** [comment]
Done, fixed in 2.4.0.
