### ISSUE TITLE
The column name hover is annoying

### ISSUE THREAD

**Issue by trungphan** [mechatroner/vscode_rainbow_csv#113]
It's important to know the column name sometimes. But constantly showing the column name when hovering the text is annoying. Can the column name be displayed in a different place? Or at least, make the hovering behavior less intrusive, for example, only show the column name when hovering the first character of the column in a row instead of anywhere.

**Comment by mechatroner** [comment]
Hi, you can disable the tooltip in the extension settings (`enable_tooltip` option).

**Comment by mechatroner** [comment]
Thanks, putting it into the status bar sounds reasonable - this is the way this feature works in Vim and Sublime Text, the only thing is that it will not work on hover but instead always show the info based on the current cursor position. I am currently working on implementation, and will probably enable it by default, stay tuned!

**Comment by trungphan** [comment]
Thank you very much. This will be awesome.

**Comment by mechatroner** [comment]
Done. The cursor column info in the statusline is now available and enabled by default starting from version 2.4.0.
