### ISSUE TITLE
Rightclick context menu no "set as Rainbow separator"

### ISSUE THREAD

**Issue by JohnDoe2991** [mechatroner/vscode_rainbow_csv#115]
Since version 2.2.0 the context menu option "set as Rainbow separator" is gone.  Is it possible to add it back in?
Screenshot V2.3.0:
![2022-05-11 09_16_48-Window](https://user-images.githubusercontent.com/24862620/167792728-637372cc-d800-43aa-adf6-6f015688bbb8.jpg)

Screenshot V2.1.0:
![2022-05-11 09_15_31-Window](https://user-images.githubusercontent.com/24862620/167792788-ad7f63f6-b023-4514-96d4-f2569c67de1c.jpg)

**Comment by mechatroner** [comment]
Hello, 
We disabled this per this pull request: https://github.com/mechatroner/vscode_rainbow_csv/pull/109 this was basically done to avoid context menu pollution, so it doesn't work now for non-text files: https://github.com/mechatroner/vscode_rainbow_csv/blob/master/package.json#L127  
Could you please tell me more about your use case, what filetypes do you need this feature to work with?

**Comment by JohnDoe2991** [comment]
I have several different non-standard CSV files in different projects.
Like for example a CSV with a Python array in it:
`1;2;3;4;[0x00, 0x01,0x02]`
Or for example a CSV with no Escaping:
`1,2,3,4,0x00;0x01;0x02,5,6,7`

The separator always changes depending on the file/project I'm working on, and the chance is 50% that it will auto detect the right seperator.
The context menu was a very convinient way to select the desired separator.

Would it be possible to enable the context menu entry not only for plaintext but also for CSV?

**Comment by mechatroner** [comment]
Fixed this in version 2.4.0. Non-csv and non-plaintext files still won't have the context menu, although this can be changed if there is a reasonable use case.
