### ISSUE TITLE
CI/CD automate publishing to Open-VSX.org

### ISSUE THREAD

**Issue by elgalu** [mechatroner/vscode_rainbow_csv#116]
#102 Open-VSX publishing is out of date (again)

**Comment by mechatroner** [comment]
Sorry! And thanks for the reminder. I Just updated the open-vsx version, I actually planned to do this anyway, just waited for enough meaningful changes to accumulate. I also added open-vsx deployment instructions to the DEV_README.md so next time it would be easier for me to remember what to do.
