### ISSUE TITLE
RBQL window won't open when working with large files

### ISSUE THREAD

**Issue by rschindhelm-haba** [mechatroner/vscode_rainbow_csv#118]
Reproduction:

1. Set "Large File Optimizations" to "False" to enable handling of larger files.
2. Open a large CSV file - in my case the file has a size about 60 MB and > 350.000 lines with about 160 characters per record in it.
3. Try to open RBQL window to perform a query.

Expected behavior:

RBQL window would show, providing options to query the data in the opened file.

Actual behavior:

Nothing happens. There's no RBQL window opening, and no popup saying "file too large" etc.

**Comment by rschindhelm-haba** [comment]
Update:
The only feature working seems to be the coloring. "Align CSV columns" does not work either.

**Comment by KeremAslan** [comment]
I also have this issue with a 64 MB, 195K rows file

**Comment by mechatroner** [comment]
Sorry for a late reply,
This is a known feature of VSCode, see: https://stackoverflow.com/a/53643761/2898283
You can follow the suggestion there and set `"editor.largeFileOptimizations": false`, but this may result in poor performance in some cases.

**Comment by rschindhelm-haba** [comment]
Thank you for the reply. So basically there's nothing I can do about it, as I already set the large file optimizations to false. That's a pity, but I can live with that constraint.

I'll close this issue. You may feel free to re-open it if you find a workaround.

**Comment by mechatroner** [comment]
For posterity: there is another limit around 50MB above which extensions have no access to the underlying files, see  https://github.com/microsoft/vscode/issues/31078
I subscribed to the issue just in case.
