### ISSUE TITLE
Implement sticky scroll for header

### ISSUE THREAD

**Issue by BeneKenobi** [mechatroner/vscode_rainbow_csv#124]
It would be great if this extension supported the "sticky scroll" feature (https://code.visualstudio.com/updates/v1_71#_sticky-scroll) for the detected header line.

**Comment by mechatroner** [comment]
Wow, thanks! I didn't know this feature exist. I think this is a super cool proposal, and it is doable, I already created a prototype and it is working! I should also update the main screenshot to advertise the feature because as I understand the sticky scroll is not enabled by default.

**Comment by mechatroner** [comment]
Done and released with version 3.5.0.
