### ISSUE TITLE
Poor alignment when mixing Chinese and English

### ISSUE THREAD

**Issue by 1284685832** [mechatroner/vscode_rainbow_csv#125]
![image](https://user-images.githubusercontent.com/21006190/208233504-2fe9cba5-f6a2-4e9f-b32f-bb73b27c8158.png)
In the image above, the plugin seems to equate the width of Chinese character with the English character, without inserting the correct amount of spaces, which is clear in the comparison of the second line and the third line: Three spaces are inserted after "1" and " 一", and normally there should be two spaces after "一".
I'm sure I've used a monospace font with a width ratio of 2:1 for Chinese characters to English characters, no problem on other occasions.

**Comment by mechatroner** [comment]
Done, see #69. Although apparently 2:1 ratio doesn't quite work in some environments, see https://stackoverflow.com/a/7221188/2898283
