### ISSUE TITLE
Option to ignore parsing issues on first line

### ISSUE THREAD

**Issue by skyhirider** [mechatroner/vscode_rainbow_csv#13]
I am regularly working with .csv files where the first line contains the encoding, usually UTF-8.

Would you be willing to add an option to ignore parsing issues if there are no separators in the first line?

**Comment by mechatroner** [comment]
Hello!
Thanks for feedback!
Does this mean that the actual header is in the second line, or there are no header at all? Could you provide a screenshot to illustrate the problem? Or just type a sample of .csv file with encoding at the first line, I am curious how it looks like. Do you know what software produces such files? Are they described somewhere or standardized? 
BTW did you know about "SetVirtualHeader" command? It is described in the README file. It allows you to use custom column names and should fix the tooltip errors.

**Comment by skyhirider** [comment]
Thanks for the reply!

Did not know about the command, thou not sure if that would help me.

Here is an example file, I get it when exporting queries from a database. 
```
UTF-8
header1,header2,header3
data1,data2,data3
```
No data separators in the first line, only encoding.

The database is not publicly available unfortunately, but I believe it is an Oracle database. Unsure if it is standardized but that is how it behaves for us locally.

**Comment by mechatroner** [comment]
I see. So "SetVirtualHeader" will work in your case.
Also when #12 is done, it will be possible to disable tooltip in all files by default, this will be useful if first-line-encoding files is your most common use case, and enable tooltip with "SetVirtualHeader" only when you really need it.
And of course there is an option to just delete the first line, if you don't mind modifying the file.

**Comment by mechatroner** [comment]
In version 1.1.1 "comment prefix" config option was added. So now it possible to specify `UTF-8` as comment prefix as a workaround to avoid parsing problems.

**Comment by skyhirider** [comment]
Much appreciated, thanks @mechatroner !
