### ISSUE TITLE
single space as delimiter

### ISSUE THREAD

**Issue by kew24** [mechatroner/vscode_rainbow_csv#131]
Currently, with whitespace as a separator, consecutive whitespaces are merged. However, if I have a file that is delimited by _single spaces_, I can't seem to make it recognize I want a single space as my delimiter.

Is there any way to specify I want a _single space character_ as my delimiter, or is this restricted to just any whitespace? Maybe adding a setting to toggle off consecutive whitespace merging would work instead. Let me know what you think.

Thanks for this extension — it's been super helpful.

**Comment by mechatroner** [comment]
Done, starting from version 3.12 you can use `Set rainbow separator` command to select the whitespace separator with a non-merging policy in the new UI.

**Comment by kew24** [comment]
Awesome, thanks for adding this in!
