### ISSUE TITLE
rainbow can not be uninstalled because it is installing

### ISSUE THREAD

**Issue by SUNSONG111** [mechatroner/vscode_rainbow_csv#133]
Type: <b>Bug</b>

rainbow can not be uninstalled because it is installing

Extension version: 3.5.1
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22624
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.18.0-348.7.1.el8_5.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.88GB (17.59GB free)|
|Process Argv|--crash-reporter-id f64ca1ec-329c-4877-a31b-213bac1bbc55|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 202.199.7.67_sunsong|
|OS|Linux x64 4.18.0-348.7.1.el8_5.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 5215 CPU @ 2.50GHz (40 x 2500)|
|Memory (System)|502.35GB (387.99GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
6233i204:30672705
pythonb192:30669360
functionswalk:30687959
pythonms35:30686772

```

</details>

**Comment by mechatroner** [comment]
Hello,
Does this error show up often for you?
If so you should consider opening a ticket at https://github.com/microsoft/vscode repo, Rainbow CSV doesn't handle installation/uninstallation itself instead it delegates this to the VSCode editor.
