### ISSUE TITLE
Support for Azure Data Studio

### ISSUE THREAD

**Issue by davidpetric** [mechatroner/vscode_rainbow_csv#135]
Great extension.

Are there any plans to develop a version for Azure Data Studio?

**Comment by mechatroner** [comment]
Thank you for the feedback!
I don't think I am ready to develop another version for Azure Data Studio, but if someone else wants to do this they have my full support! Also, I am totally cool if they would use the "Rainbow CSV" name for that extension if they wish to.

**Comment by davidpetric** [comment]
Looks like it's working with minimal effort. 

I just copied the `v3.0..0` version folder from VS Code extension folder( `C:\Users\your.username\.vscode\extensions\` on Windows) to the Azure Data Studio extensions folder( `C:\Users\your.username\.azuredatastudio\extensions` on Windows) and it works. 

The latest version(at this time `v3.7.0`) complains about the 'a engine' of Azure Data Studio not being compatible with the extension.

Thanks!

**Comment by mechatroner** [comment]
I am glad it worked!
