### ISSUE TITLE
Inconsistent Highlighting / RBSQL not returning anything

### ISSUE THREAD

**Issue by kupdegrove** [mechatroner/vscode_rainbow_csv#136]
I'm running Rainbow CSV version 3.7.0 in VS Code 1.77.3 on Windows 10.0.1.10944 Build 19044. I have 3 pipe-delimited .csv files. Highlighting works correctly on 2 out of 3 but does nothing on the third (CSV Lint shows no errors on the third). The extension is loading because the status bar changes.

In addition to this, the RBSQL query function returns no results when it's clear that it should. The syntax is very simple and correct: 
`SELECT * WHERE a1 == "20"` . The table clearly shows values of "20" in the RBSQL console but nothing returns in the result set.

Oddly enough, a custom Javascript function I added to **_.rbql_init.source.js_** works as expected (correct results are returned): 
```
function isNotAscii(str) {
    var regex = /[\x80-\xFF]/;
    var result = str.match(regex);
    if (result == null) {
        result = "False";
    } else {
        result = "True";
    }
    return result;
}
```
**What I've tried:**

- Query on all three different files (no change)
- Removing the custom function and reloading (no change)
- Uninstalling and reinstalling the extension (no change)

Any assistance would be greatly appreciated

**Comment by mechatroner** [comment]
Could you please send me the obfuscated content of the third file (without any sensitive data) and its file name that would allow me to reproduce the problem if possible? Thanks!
BTW did you try to set the filetype for the third file manually? It should be `csv (pipe)`

**Comment by kupdegrove** [comment]
Apologies. I wish I had seen this before emailing. I've attached the file here. Nothing sensitive about it, it's available for public download. As OP indicates, RBSQL only working with my custom function. Simple queries return nothing. 
[abcdata_MST_20230426_1143.csv.tar.gz](https://github.com/mechatroner/vscode_rainbow_csv/files/11338888/abcdata_MST_20230426_1143.csv.tar.gz)

**Comment by mechatroner** [comment]
No worries and thank you for sending the file!
I think I know what the problem is - VSCode doesn't highlight files if they are bigger than a certain threshold but you can can this by disabling the `Editor:Large File Optimizations` setting, see https://github.com/mechatroner/vscode_rainbow_csv#working-with-large-files

**Comment by kupdegrove** [comment]
Thank you. That solved the highlighting option but I still have the RBQL issue. Do I need to repost in that repo?
