### ISSUE TITLE
File Modification

### ISSUE THREAD

**Issue by AyomideA-S** [mechatroner/vscode_rainbow_csv#137]
When I use the **Align** feature on a CSV file, it actually alters the file itself. This is reproducible when you do this alignment and then import the data into Pandas or something.
You'll figure out that whitespaces are part of your headers.

And once again, this is a very helpful extension by the way.
Thanks! ❤️️

**Comment by mechatroner** [comment]
Thanks for the feedback!
The only workaround is to enable `align_in_scratch_file` setting - it would keep the original file unmodified.

**Comment by AyomideA-S** [comment]
Thanks a lot man!
