### ISSUE TITLE
Line length

### ISSUE THREAD

**Issue by umamibeef** [mechatroner/vscode_rainbow_csv#140]
I was not able to find this through search. How do I set the maximum line length? I'm guessing it's the linter doing this, but it doesn't like it when a column exceeds a certain number of characters, causing it to automatically create a new line for me. I don't want this behaviour.

Thanks in advance!

**Comment by mechatroner** [comment]
Rainbow CSV doesn't have this feature, this is likely built-in VSCode word-wrap functionality, there seem to be a few settings related to the word-wrap behavior that you can adjust including `"editor.wordWrap"` and `"editor.wordWrapColumn"` see https://stackoverflow.com/a/60060509/2898283 and https://linuxpip.org/vscode-enable-word-wrap/

**Comment by umamibeef** [comment]
I figured it out, it's indeed CSVLinte complaining, but it's about an un-even number of fields. Now to figure out why it's not respecting my comment character...
