### ISSUE TITLE
Non-aggregate "group by"  doesn't work as expected

### ISSUE THREAD

**Issue by quarnster** [mechatroner/vscode_rainbow_csv#144]
testdata:

```
hello,world
hello,class
hello,man
goodbye,class
``` 

`select * group by a1` and `select * group by a2` both return all entries

**Comment by mechatroner** [comment]
Thank you very much for reporting.
Looking into this.

**Comment by mechatroner** [comment]
I fixed this (surprisingly it was just a single line change) and added RBQL unit tests so it won't break again. 
To me, non-aggregating GROUP BY seems to be quite an exotic mode (probably this is why I completely forgot to implement and test it). And actually different DB vendors have different implementations of it, the most common one, it seems, is to just disallow "bare" columns in SELECT altogether (https://stackoverflow.com/questions/20074562/group-by-without-aggregate-function), while SQLite for example allows them and just chooses an arbitrary value from each bare column/group (https://stackoverflow.com/questions/67536804/are-there-in-guarantees-about-the-non-aggregated-columns-in-a-group-by-query).  RBQL will have a middle ground approach - it allows bare values in SELECT if they are identical for each grouping key, but if there are 2 or more different values in any group the query would fail with an error.

**Comment by quarnster** [comment]
FWIW MySQL also does what SQLite does, but TIL that it's [not standard](https://medium.com/@riccardoodone/the-love-hate-relationship-between-select-and-group-by-in-sql-4957b2a70229). I'm 100% ok with the suggested fix.

**Comment by quarnster** [comment]
Just had an idea that maybe a new or existing aggregate function could accomplish the mysql/sqlite functionality. Like `select ANY(a1),a2 group by a2` in case anyone ends up in this issue and needs it.

**Comment by mechatroner** [comment]
ANY() sounds like a good idea, I will probably do it at some point.

**Comment by mechatroner** [comment]
Update: `ANY_VALUE` is now available in version 3.8.0.
