### ISSUE TITLE
RBQL with Python error

### ISSUE THREAD

**Issue by cbconne** [mechatroner/vscode_rainbow_csv#148]
![image](https://github.com/mechatroner/vscode_rainbow_csv/assets/44186296/55c601c7-0efe-4912-a8bd-90f7d81d5a0e)

As shown in the screenshot.
It looks like I don't have Python installed or configured in the system path, but that's not.

**Comment by mechatroner** [comment]
Thanks for reporting! I think I know what the problem is - the extension tries to run `python` instead of `python3` command - I wrongly assumed that any Python installation would have that alias defined. I will fix it in the next release, meanwhile, you can create python -> python3 symlink and it will probably work.

**Comment by cbconne** [comment]
> Thanks for reporting! I think I know what the problem is - the extension tries to run `python` instead of `python3` command - I wrongly assumed that any Python installation would have that alias defined. I will fix it in the next release, meanwhile, you can create python -> python3 symlink and it will probably work.

Yes, I created a symlink, then it work. But there is still a problem.
With JS:
![image](https://github.com/mechatroner/vscode_rainbow_csv/assets/44186296/52bedcd6-ab01-46bf-9692-85afd8ce9165)
![image](https://github.com/mechatroner/vscode_rainbow_csv/assets/44186296/a23973f4-33fb-44b8-b80b-b5677c37ef02)
But with Python:
![image](https://github.com/mechatroner/vscode_rainbow_csv/assets/44186296/fe1af586-ecec-4ac5-83e5-bd85049144ff)
![image](https://github.com/mechatroner/vscode_rainbow_csv/assets/44186296/6f31bce1-fa6b-497d-9d94-f63136366d00)
No data was found when using the same query statement using Python.

**Comment by mechatroner** [comment]
RBQL is essentially a thin wrapper around JS or Python interpreter. Also, all CSV field variables in RBQL are strings until you convert them to something else. So in JS you can compare integers and strings and get true e.g. `'10051' == 10051`, while in Python this doesn't work, so either use
`select * where int(a1) == 10051` or `select * where a1 == '10051'`

**Comment by mechatroner** [comment]
Fixed: starting from version 3.10.0 `python3` is used first and if the invocation fails `python` is used as a fallback.
