### ISSUE TITLE
CSV Lint - check for leading/trailing spaces

### ISSUE THREAD

**Issue by rmeske** [mechatroner/vscode_rainbow_csv#15]
One of the most common cleanup of data I encounter is leading and trailing spaces in columns.  It is actually much easier to spot with Rainbow CSV, so thank you for this extension.

It would be great if the linter could identify leading/trailing spaces automatically as an option.

**Comment by mechatroner** [comment]
I like this idea. Maybe we should make this a default behavior - if the linter detects leading/trailing whitespaces, it would show a yellow-colored warning (but there would be an option to disable it, although It's hard for me to imagine a situation where leading/trailing whitespaces could be meaningful). Also we will probably need a "StripTrailingSpaces" command, which would automatically make the cleanup. What do you think about this?

**Comment by kcomplexes** [comment]
a 'StripTraillingSpaces" option would be immensely helpful for the data I work with.

![image](https://user-images.githubusercontent.com/16506704/50619139-01db0d00-0f3f-11e9-8d98-29bb7c75ce85.png)

**Comment by mechatroner** [comment]
@kcomplexes I will implement it at some point, for now you can use an RBQL query similar to this:
`select a1.trim(), a2.trim(), a3.trim(), a4.trim()`, where trim() is a JS function: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim

**Comment by mechatroner** [comment]
Available with version 1.1.1, but should be activated in context menu with "csv_lint_detect_trailing_spaces" option which is "false" by default. Also there are two new commands: "Align" and "Shrink", the later can be used to remove all leading and trailing whitespaces in all fields
