### ISSUE TITLE
Fails if file too big?

### ISSUE THREAD

**Issue by AJamesPhillips** [mechatroner/vscode_rainbow_csv#153]
Hi, I love this tool.  Really great.  Thank you.  When I open a small file it works fine but with larger files it doesn't seem to load the extension command UI buttons:

<img width="1436" alt="Cursor_and_2019Q4_csv_—_housing-data" src="https://github.com/mechatroner/rainbow_csv/assets/526509/7c34a4a2-cfc6-416d-8eeb-016af1843a1d">

The rainbow colours for the file contents renders fine (as you can see above) so the file must have been read and parsed ok.

The files in question are from here: https://statistics.gov.scot/data/domestic-energy-performance-certificates and are about 50Mb each so not that large.  If I make a subset of the file it works fine.  I thought it might be some bad character which might be breaking the extension but then the rainbow colours work so I don't know.

**Comment by mechatroner** [comment]
I've subscribed to the VSCode issue I linked to know if there are any API updates to handle this situation better. Currently, big files are completely hidden from extensions - there is no reliable way to request big file size, filename, extension, filetype, etc. So there is no way to show the message in the UI, and I don't think logging something to the debug log would have a lot of value (and again it won't probably be precise enough)

**Comment by AJamesPhillips** [comment]
Ah got it.  Thank you.  Ok I'll close this.  I hope they improve the API around this.
