### ISSUE TITLE
Enable tooltip column names is not working

### ISSUE THREAD

**Issue by flaviu22** [mechatroner/vscode_rainbow_csv#157]
I have the following csv:

<hardware_configuration>;<function_name>;<machine_unit>
11111111111111111111111111111111;STATUS;TRDD;

But when I do a hover over an element, I have no column name in the tooltip:
![image](https://github.com/mechatroner/vscode_rainbow_csv/assets/37621568/206725b6-23db-4730-a0c4-57087b23d5e0)

Even though I have that setting enabled:

![image](https://github.com/mechatroner/vscode_rainbow_csv/assets/37621568/05046f36-a6bf-4d39-9056-802638ff3fab)

How can I overcome this?

**Comment by mechatroner** [comment]
Thanks for the bug report, data, and screenshot - I was able to easily reproduce the bug. Looking into this.

**Comment by flaviu22** [comment]
Thanks, has been fixed!

**Comment by flaviu22** [comment]
Thanks, has been fixed!

**Comment by Bijay774** [comment]
[javascript(url<details<summary>Details</summary><p>html/</p</details>I have the following csv<<hardware_configuration><function_name<machine_unit>/STATUS;TRDD;`**
