### ISSUE TITLE
Extremely bad performance with 100kb tsv

### ISSUE THREAD

**Issue by the21st** [mechatroner/vscode_rainbow_csv#20]
rainbow csv 0.5.0
vscode 1.26.1
file: https://www.dropbox.com/s/h05utmwi8wa9gwb/slow-perf-2.tsv?dl=1

**Comment by mechatroner** [comment]
Thank you for bug report!
I've opened your file both in windows and linux version of VSCode, but was unable to reproduce slow performance. The file gets highlighted immediately and tooltip works as expected. In your case which part is working slow: syntax highlighting or tooltip? Could you try to open the file on another computer or with other extensions disabled and settings reset to default? Maybe there is something in your setup which interferes with Rainbow CSV and I really want to find out what it is.
BTW number of fields in your file is not consistent, see the table below:
{code}
line,fields
1,14
2,14
3,14
4,14
5,26
6,14
7,13
8,14
9,14
10,14
11,14
12,14
13,14
14,14
15,14
16,14
17,14
18,14
19,19
20,14
21,14
22,13
23,14
24,13
25,14
26,14
27,14
28,14
29,14
30,14
31,14
32,14
33,14
34,14
35,19
36,14
37,14
38,21
39,14
40,17
41,14
{code}

**Comment by the21st** [comment]
Tried everything again and not seeing performance issues anymore, not even with the original file. Thanks for the help!

**Comment by mechatroner** [comment]
Glad it worked! Could you also update your Marketplace review, since you don't experience the problem any more?
