### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by ThomasPerraudin** [mechatroner/vscode_rainbow_csv#21]
It doesn't work for me. Find my working file in attachement. VS Code 1.27.2

[inscription.zip](https://github.com/mechatroner/vscode_rainbow_csv/files/2384236/inscription.zip)

**Comment by mechatroner** [comment]
Hi @ThomasPerraudin 
You need to manually change the syntax to "CSV (semicolon)", see #16

**Comment by ThomasPerraudin** [comment]
Yes it works. Just had to know ... Thank you.
