### ISSUE TITLE
Preface command names with "Rainbow CSV:"

### ISSUE THREAD

**Issue by yozlet** [mechatroner/vscode_rainbow_csv#22]
It's common practice to start the names of extension commands with the name of the extension. Try hitting the VSCode command prompt, then typing the name of any extension you have installed. Most of the time, you'll see a load of commands that start with the extension name, followed by a colon.

It makes it much easier to find commands that you know exist in a particular extension but can't remember the specific command. In my case, I was trying to remember the name of Rainbow CSV's grid/SQL-like view, but typing `Rainbow`, `CSV` or `SQL` didn't help, because I didn't remember `RBQL`.

**Comment by mechatroner** [comment]
Cool, Thanks!
Somehow I was not aware of this crucial feature. Just published this as 0.7.1 along with another very important fix, see the brand new [Changelog](https://github.com/mechatroner/vscode_rainbow_csv/blob/master/CHANGELOG.md)

**Comment by yozlet** [comment]
Thanks for fixing it so quickly!
