### ISSUE TITLE
If the last field is quoted, colourisation is applied in that field if it contains a commna

### ISSUE THREAD

**Issue by richardcox13** [mechatroner/vscode_rainbow_csv#27]
Test data:
```
"This is a field, with a comma", "This is another field, with a comma"
"And on another line, after comma", "The second field, colourises when it shouldn't"
````

And there is a colour change after the comma in each of the final fields (but earlier ones are OK)

![csv-colour](https://user-images.githubusercontent.com/4578827/48612755-c7fb7a80-e981-11e8-8eb2-3e107dca97c1.png)

(Latest VSCode 1.29 64bit on Windows 10)

**Comment by mechatroner** [comment]
Thanks! 
Actually, the problem here is an extra whitespace outside double quotes. If you remove it - this should fix the highlighting. CSVLint should also be able to detect the problem. I can change this issue title to "Support whitespaces outside double quoted fields".

**Comment by richardcox13** [comment]
Thanks for the update – must remember that CSV is machine, not human readable :-)

Thanks
