### ISSUE TITLE
Unreadable RBQL Console label with Light Theme

### ISSUE THREAD

**Issue by williamsp** [mechatroner/vscode_rainbow_csv#28]
Unreadable RBQL Console label with Light Theme
![screenshot from 2018-12-05 18-55-25](https://user-images.githubusercontent.com/3760416/49512034-5d25cb00-f8bf-11e8-956c-c9647fc7c336.png)

**Comment by docbiz** [comment]
More generally, I think it'd be useful if the RBQL page inherited from the user's settings (colours, fonts, etc.)...
