### ISSUE TITLE
Add option to override editor.insertSpaces for tsv only

### ISSUE THREAD

**Issue by tedypranolo** [mechatroner/vscode_rainbow_csv#29]
Is it possible to add an option to always insert tab (instead of spaces) in .tsv file, regardless of the current editor.insertSpaces setting?
I was wondering why Rainbow Csv was not coloring my new .tsv. Turns out all of my tabs were converted to spaces. I want to keep editor.insertSpaces=true for all other document but enter actual tab character in .tsv.
Thank you.

**Comment by mechatroner** [comment]
Hi @tedypranolo !
VSCode supports language-specific configuration, all you need to do is to add the following lines to your VSCode config:
```
    "[tsv]": {
        "editor.insertSpaces": false
    }
```
I've just tried it and it worked for me.
Maybe I will include this in Readme documentation.

**Comment by tedypranolo** [comment]
I didn't know that. Thank you.
