### ISSUE TITLE
seems not to work on bigger files

### ISSUE THREAD

**Issue by B0rschti** [mechatroner/vscode_rainbow_csv#3]
I have a big csv file with more then 80k lines and 34 colums (mix strings and numbers) of "," separated data.
The plugin works really well when i reduce the the line amount or copy the whole content into a new file and saves it as ".csv" file.

But when i load the original bigger file with ~80k lines x 34 rows there is now rainbow coloring.

Because i like to see outsiders in my data i appreciate this plugin.
Is it possible to investigate and "fix" / "extend" it to also to handle bigger files well on loading?

**Comment by mechatroner** [comment]
I think this could be VS Code limitation. I've just tried a random 5.6 MB file with 100K lines, and highlighting works, although lines which are located further from the file beginning takes a little longer to highlight. Could you please answer these questions: 
* What is the size of your file? (And probably you mean 34 columns not rows, right?) 
* What version of VSCode do you have (perhaps updating it to the latest version could solve the problem)? 
* What OS? 
* In your case does highlighting works at least for some of the lines?
* does VSCode show any errors?

**Comment by gabrielmathias** [comment]
I am using VS Code 1.20.1  on a MacOS Sierra machine.
A 240MB csv file with 44 columns and 1000000 lines doesn't get highlighted.
A 25MB csv file with 44 columns and 100k lines doesn't work also.
But a 14MB csv file with 44 columns and 50k lines does.

Nothing shows up on VS CODE 'PROBLEMS' panel.

**Comment by mechatroner** [comment]
Starting from VS Code version 1.23.1 there is a workaround: add `"editor.largeFileOptimizations": false` to VS Code settings to highlight large CSV files.

**Comment by mechatroner** [comment]
I've updated the README file with instructions for big files. Looks like there is nothing more I can do.

**Comment by B0rschti** [comment]
Okay, thanks for the effort. I will try this tomorrow. 

Best regards
