### ISSUE TITLE
Shrink/Align button on status bar doesn't switch to "Align" when file updated on disk

### ISSUE THREAD

**Issue by kylrth** [mechatroner/vscode_rainbow_csv#38]
My code outputs a CSV file, and then to inspect the output I click the "Align" button on the status bar. But when I rerun my code so that the file is overwritten, I have to click "Shrink", observe the error "No trailing whitespaces found, skipping", click away from the CSV file, and then click back in. At that point, the button has changed to "Align" again and works as expected.

**Comment by mechatroner** [comment]
Thanks! I will fix it in the next release.

**Comment by mechatroner** [comment]
BTW, while I am fixing this you can use "RainbowCSV: Shrink" and "RainbowCSV: Align" commands directly.

**Comment by mechatroner** [comment]
I just published version 1.2.0 which fixes this problem. It doesn't detects file updates on disk though, but now you don't have to click away: in case of "No trailing whitespaces found, skipping" you can immediately click again and it should work.
