### ISSUE TITLE
Tilde is misspelled throughout

### ISSUE THREAD

**Issue by curtisgibby** [mechatroner/vscode_rainbow_csv#40]
Everywhere you've got `tilda`, it should be spelled `tilde`:

- https://github.com/mechatroner/vscode_rainbow_csv/blob/4e3c887c20dbfcddd8c5f90c2c45940a85922c26/package.json#L25
- https://github.com/mechatroner/vscode_rainbow_csv/blob/4e3c887c20dbfcddd8c5f90c2c45940a85922c26/package.json#L163-L167
- https://github.com/mechatroner/vscode_rainbow_csv/blob/13ddb66aa3f8abc1688a535497b0f2c3f010cd0e/README.md#L52
- https://github.com/mechatroner/vscode_rainbow_csv/blob/6fc9ea05e174d229386e345f41b5d943e886e367/extension.js#L15

**Comment by mechatroner** [comment]
Thank you, @curtisgibby ! In Russian, which is my native language, it is called "Тильда" (pronounced as Tilda), and I forgot to check the English name. Will fix by the next release.

**Comment by mechatroner** [comment]
Fixed in version 1.3.1
