### ISSUE TITLE
RBQL Console does not open for new unsaved files

### ISSUE THREAD

**Issue by gschneider-r7** [mechatroner/vscode_rainbow_csv#41]
When opening a new empty tab in VS Code, pasting CSV content, and then selecting the proper language mode most functions seem to work fine (color highlights, align, shrink, set virtual header). However the RBQL command and status bar button do nothing. After saving the new file to disk the RBQL Console can be opened by command or status bar button.

I didn't do extensive testing, but I noticed this while working with simple 3-column, ~2500 lines of data.

macOS High Sierra 10.13.6
Visual Studio Code 1.37.1
Rainbow CSV 1.2.0

**Comment by mechatroner** [comment]
Thanks for bug report! RBQL works with files on disks (it is possible to make JS-based version to work with VSCode buffers, but Python version would still need a file on disk), so for now the extension will just show a relevant error in cases like this.

**Comment by gschneider-r7** [comment]
An error message would be sufficient, thank you. 👍

**Comment by mechatroner** [comment]
I just published version 1.3.1 which shows the error, but I will think about implementing the following features which should improve experience for the usecase you've described:
1. CSV dialect autodetection whenever a large text fragment is being copied into a new empty buffer.
2. If RBQL is executed for a new buffer which is not associated with a file, the extension will automatically copy it's content into a temporary file and use it to run RBQL.

**Comment by mechatroner** [comment]
Done. I just deployed new version 1.4.0 which supports this.
