### ISSUE TITLE
Add hints for the RBQL navigation arrows

### ISSUE THREAD

**Issue by john-aws** [mechatroner/vscode_rainbow_csv#42]
The first time you use RBQL console and you're viewing a small CSV file, the RBQL console shows some arrows to the left of the 1st column. The iconography is unusual and it's not immediately obvious what these icons represent. There is no hint and clicking them does nothing (for a small CSV file).

<img width="356" alt="rbq-arrows" src="https://user-images.githubusercontent.com/3178883/67121982-c0a8a680-f1ba-11e9-8987-e1f4a7ef0997.png">

I'm assuming these icons are clickable and their function is go to top, go up one page, go down one page, go to end. It would be helpful to add flyover hints.

**Comment by mechatroner** [comment]
Done
