### ISSUE TITLE
Not working on MacOS 10.13.6

### ISSUE THREAD

**Issue by ozjsean** [mechatroner/vscode_rainbow_csv#43]
Issue Type: <b>Bug</b>

cannot use extensions
MacOS 10.13.6
Extension "Rainbow CSV"

Extension version: 1.3.1
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: disabled_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ozjsean** [comment]
Sorry, it was only a specific CSV issue
Do you know what kind of CSV is unsupported?

**Comment by mechatroner** [comment]
All CSVs are supported except for very large ones, there is a VSCode limitation on file size: 300K lines and 20MB or 50 MB, see https://github.com/mechatroner/vscode_rainbow_csv#working-with-large-files If you find a small file where it doesn't work please post here it's content without sensitive data. @ozjsean how big was the file for which Rainbow CSV didn't work?

**Comment by ozjsean** [comment]
Thank you for the quick response!
over 150mb, no wonder it doesn't work

Pity that I cannot use VSCode (with Rainbow CSV!)
Any suggestions on large files? No choice but to use another editor?

**Comment by mechatroner** [comment]
There is an option to preview first 1MB of your file in the VSCode Explorer, just right click on the huge CSV file and select "Preview Big CSV head". 
There is also exist Rainbow CSV versions for Vim and Sublime Text 3 - both of them should be able to handle 150 MB files, sometimes I open 1GB files in Vim.

**Comment by ozjsean** [comment]
>just right click on the huge CSV file and select "Preview Big CSV head".
May I ask where exactly this is?
Tried right-clicking the file inside VSC's explorer pain and in Mac's file explorer although could not find this,,,

**Comment by mechatroner** [comment]
This is how it looks like in my editor
![Screenshot (36)](https://user-images.githubusercontent.com/5349737/67821241-b3c96400-fa92-11e9-99ed-ab8be4bc3199.png)
Just make sure you have preview feature enabled in Rainbow CSV settings (it is enabled by default, but maybe it got disabled for some reason)

**Comment by ozjsean** [comment]
Found it! Thank you.

The issue was, I was opening a single file, not a folder containing the files.
It seems like you don't have the option to preview when opening a file. the preview option was available after opening by the folder.

Thank you once again
