### ISSUE TITLE
Add table editor like "vscode-edit-csv"

### ISSUE THREAD

**Issue by chatelao** [mechatroner/vscode_rainbow_csv#44]
To avoid delimiter edit mistakes, allow a Table/Excel view similar to https://github.com/janisdd/vscode-edit-csv

**Comment by mechatroner** [comment]
Sorry, but this is beyond the scope of Rainbow CSV. Also I don't have time to implement and support this feature. BTW why you can't just use vscode-edit-csv if it does exactly what you ask?
