### ISSUE TITLE
Allow first row to be column names

### ISSUE THREAD

**Issue by chatelao** [mechatroner/vscode_rainbow_csv#45]
Goal
- Allow the names in the first row to be used as keys in the RBQL

**Comment by mechatroner** [comment]
Hi @chatelao, this is one of the long planned features. Actually named variables were just added to RBQL ( https://github.com/mechatroner/RBQL/issues/6 ) So if all goes well the new feature will be soon available in the extension.

**Comment by mechatroner** [comment]
Done. Column names are supported in version 1.4.0 which I just deployed.
Thy syntax is `a.good_alphanumeric_column_name` and `a["arbitrary column name!"]`
