### ISSUE TITLE
Support Copy-Paste from Excel, similar the Markdown - Excel module

### ISSUE THREAD

**Issue by chatelao** [mechatroner/vscode_rainbow_csv#46]
Support csv to Markdown:
- https://thisdavej.com/copy-table-in-excel-and-paste-as-a-markdown-table/

Excel is the best editor for tables, so supporting would be great.

**Comment by mechatroner** [comment]
I agree that this feature can be useful in some situations, but it is beyond the scope of Rainbow CSV. I just don't have enough resources to implement and support this functionality.
