### ISSUE TITLE
Wrong rendering of pipe

### ISSUE THREAD

**Issue by luca1010** [mechatroner/vscode_rainbow_csv#48]
If you open a file with extension CSV, pipe separator some pipes are rendered as / 
selecting the / the | are selected, therefore the character is shown as / but treated as | 

To test it you can use this simple one line csv

a|b|c|d|e|f|

the | between d and e and the last | in my vs code (latest version) are rendered as /

**Comment by mechatroner** [comment]
Hi @luca1010 ,
Thanks for bug report! 
What if you open the file with Rainbow CSV disabled, do the pipe chars are rendered as slashes or this only happens with CSV highlighting enabled? Another possibility is that maybe there are some hidden non-ascii chars in the original file, if you copy the line you provided `a|b|c|d|e|f|` and paste it back into the editor, will it be rendered with slashes? If not, can you hexdump the problematic lines of your original file?

**Comment by luca1010** [comment]
Hi,

The issue does not happen if I disable the extension.

I checked an hex dump of the file, no hidden chars.
You can copy exactly the line I posted, or write it from scratch to
reproduce the issue.
If you write or paste it it it is rendered correctly. Then you save the
file, close the tab, open the file and you get some slash.




Il lun 2 dic 2019, 14:35 Dmitry Ignatovich <notifications@github.com> ha
scritto:

**Comment by mechatroner** [comment]
Thank you, @luca1010
I tried, but I can't reproduce the problem in VSCode 1.40.2 / Windows 10:
![Screenshot (41)](https://user-images.githubusercontent.com/5349737/70014692-6042ae00-1549-11ea-89b2-abee70f010fd.png)

Are you also using VSCode 1.40.2? What OS are you using?

**Comment by mechatroner** [comment]
@luca1010 could you please also try to reproduce it with other extensions disabled, just VSCode 1.40.2 + Rainbow CSV ? Maybe it's a combination of different components that causes the problem.

**Comment by luca1010** [comment]
Hi,

It seems that it conflicts with one dark pro extension.
With that disabled the csv is shown correctly.

Regards

Luca

Il mar 3 dic 2019, 05:51 Dmitry Ignatovich <notifications@github.com> ha
scritto:

**Comment by mechatroner** [comment]
So what happens here is that "One dark pro" uses "italic" font to highlight "comment" and "variable.parameter" tokens. You can see this with other file types (e.g. in JS files) where pipe characters in comment lines will look a little tilted. But if you enter an actual "slash" character it will look much more diagonal than the italicized pipes, see my screenshot:
![Screenshot (43)](https://user-images.githubusercontent.com/5349737/70196863-03293280-16d8-11ea-988a-277895e946ef.png)
If you really want, you can set your own custom colors for rainbow fields, see instructions here: https://github.com/mechatroner/vscode_rainbow_csv/blob/master/test/color_customization_example.md  But don't forget to remove `"fontStyle": "italic"` directives :smirk:
