### ISSUE TITLE
Also color inside of markdown files

### ISSUE THREAD

**Issue by mhkeller** [mechatroner/vscode_rainbow_csv#50]
It would be nice if this extension also colored csv files inside of markdown files, the same way that code blocks get colored.

For example:
![Screen Shot 2020-01-10 at 5 26 11 PM](https://user-images.githubusercontent.com/498744/72190725-5032af80-33ce-11ea-84f8-2687885180c0.png)

**Comment by mechatroner** [comment]
I agree that it would be nice to have such coloring in markdown files too, but this feature is clearly beyond the scope of Rainbow CSV extension.

**Comment by mhkeller** [comment]
I guess we can disagree on that. The scope of this extension is a broad csv toolkit, given that includes not just highlighting but also a fully-featured query interface. Extending syntax highlighting to CSVs in markdown files seems pretty natural to me, especially since this is a standard feature in other languages. If anyone knows of an alternative that does this, please let me know.
