### ISSUE TITLE
Clean up the Query History

### ISSUE THREAD

**Issue by sollygit** [mechatroner/vscode_rainbow_csv#52]
Hi,
I even uninstalled the ext. from vscode and deleted cache, however I couldn't get rid of my old Query History.
Maybe you could provide the location of the Query History so users can manually delete it, until it is fixed.

![image](https://user-images.githubusercontent.com/30820950/76300495-832eec00-6308-11ea-9f67-99b128de006c.png)

**Comment by mechatroner** [comment]
I think it is not possible to manually delete the history, Rainbow CSV uses a special "globalState" object ( https://code.visualstudio.com/api/references/vscode-api#ExtensionContext ) to store the history. This "globalState" is managed by VSCode, and could be stored as a binary file. I was unable to find any info on where to find it or how to edit it manually. I will add history cleanup feature in the next version.

**Comment by sollygit** [comment]
Thank you for your reply.
I was able to manually delete vscode cache and that's resolved now.

Regards
Solly.

**Comment by mechatroner** [comment]
Done. "Clear history" button is now available with version 1.7.0
