### ISSUE TITLE
Requesting RBQL #18 to be merged into rbql_core of the plugin (Like Operator)

### ISSUE THREAD

**Issue by metmac** [mechatroner/vscode_rainbow_csv#54]
Hey Dmitry,
Love this plugin and the idea behind RBQL, super handy in a pinch.

Would be super handy to use the LIKE function you just merged into https://github.com/mechatroner/RBQL/issues/18 in vscode.
 
If it is as simple as dropping in to `rbql_core` I'd be happy to submit a PR.

**Comment by mechatroner** [comment]
Hi @metmac, I appreciate your feedback!
I will definitely add LIKE function to Rainbow CSV, but it is not as simple as just merging the code, I also need to test it all together and publish to the VSCode Marketplace, and I am not quite ready to do this right now, even if it sound simple, each release is actually a challenging process, and I prefer to minimize the number of releases. So I plan to add a couple more features and then publish them all together.

**Comment by mechatroner** [comment]
Done! like() function is now available with version 1.7.0
