### ISSUE TITLE
added $ as a separation character but it is not detecting it

### ISSUE THREAD

**Issue by ppazos** [mechatroner/vscode_rainbow_csv#58]
I open a CSV with $ as separator and not detecting it as a separator

**Comment by mechatroner** [comment]
Unfortunately Rainbow CSV doesn't currently support "$" separator, see the table of supported separators here: https://github.com/mechatroner/vscode_rainbow_csv#supported-separators  I will probably add "$" in the next version. My ultimate goal is to support all possible separators and sequences of separators, but this would require adjustment of VSCode core functionality, see #1

**Comment by mechatroner** [comment]
This should work now starting from version 3.0.0
