### ISSUE TITLE
Changing the colors using provided json settings does effect all other color customizations

### ISSUE THREAD

**Issue by bahmanashtari** [mechatroner/vscode_rainbow_csv#60]
Is there a way to change the colors without interfering with the existing color/font customizations in setting.json?

**Comment by mechatroner** [comment]
Did you try to use the instruction from here: https://github.com/mechatroner/vscode_rainbow_csv/blob/master/test/color_customization_example.md ? I don't see how it can interfere with other customization since this should only affect RainbowCSV - specific scope names.

**Comment by bahmanashtari** [comment]
Yes, that's exactly what I used as a reference to try to change the colors. Here's the relevant section of my existing setting for some custom formatting for comments, which gets interfered with the settings for RainboxCSV.

`"editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [
                    "comment"
                ],
                "settings": {
                    "fontStyle": "italic",
                    "foreground": "#585858"
                }
            }
        ]
    },`

**Comment by mechatroner** [comment]
I haven't seen your settings.json file, but I suspect that you have two conflicting `"editor.tokenColorCustomizations"` entries in it. Please make sure that you have only one `"editor.tokenColorCustomizations"."textMateRules"` entry, basically you should have "comment" and Rainbow CSV customization settings combined into a single array of "textMateRules", like this:
```
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            { "scope": [ "comment" ], "settings": { "fontStyle": "italic", "foreground": "#585858" } },
            {
                "scope": "rainbow1",
                "settings": {
                   "foreground": "#E6194B"
                }
            },
            {
                "scope": "keyword.rainbow2",
                "settings": {
                   "foreground": "#3CB44B",
                   "fontStyle": "bold"
                }
            },
            {
                "scope": "entity.name.function.rainbow3",
                "settings": {
                   "foreground": "#FFE119",
                   "fontStyle": "italic"
                }
            },
            {
                "scope": "comment.rainbow4",
                "settings": {
                   "foreground": "#0082C8",
                   "fontStyle": "underline"
                }
            },
            {
                "scope": "string.rainbow5",
                "settings": {
                   "foreground": "#FABEBE"
                }
            },
            {
                "scope": "variable.parameter.rainbow6",
                "settings": {
                   "foreground": "#46F0F0",
                   "fontStyle": "bold"
                }
            },
            {
                "scope": "constant.numeric.rainbow7",
                "settings": {
                   "foreground": "#F032E6",
                   "fontStyle": "italic"
                }
            },
            {
                "scope": "entity.name.type.rainbow8",
                "settings": {
                   "foreground": "#008080",
                   "fontStyle": "underline"
                }
            },
            {
                "scope": "markup.bold.rainbow9",
                "settings": {
                   "foreground": "#F58231"
                }
            },
            {
                "scope": "invalid.rainbow10",
                "settings": {
                   "foreground": "#FFFFFF"
                }
            }
        ]
    },
```

**Comment by mechatroner** [comment]
@bahmanashtari did this solution work for you?

**Comment by bahmanashtari** [comment]
@mechatroner My apologies for this late response. I truly appreciate your support, this is pretty amazing. and yes it did work. Thanks much!

**Comment by mechatroner** [comment]
@bahmanashtari glad to hear that!
