### ISSUE TITLE
Autodetection doesn't work on comma separated file in Plain text language mode

### ISSUE THREAD

**Issue by sasshi-i** [mechatroner/vscode_rainbow_csv#61]
# Reproduction procedure
* Turn on VS code following environment
macOS Catalina: 10.15.2
VS code version: 1.45.1
Rainbow CSV version: 1.7.0

* Click New file on VS Code to create new file  with no extension (I created following file)

File name: autodetection

* Put following data into file which created before(I attached file which is zipped file I tested)
[autodetection.zip](https://github.com/oss-gate/workshop/files/4774249/autodetection.zip)

```
test,test2,test3
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
aaa,bbb,ccc
```

* Confirmed Language mode is Plain text in VS code
<img width="1391" alt="スクリーンショット 2020-06-13 16 42 10" src="https://user-images.githubusercontent.com/28973144/84563237-0131e180-ad95-11ea-96b2-8c8cb207f9d8.png">

# Expected Outcome
Data is colored because autodetection worked

# Actual Outcome
Data is not colored

# About rainbow_csv.autodetect_separators setting
Autodetect separators is set as attached image. Rainbow CSV setting has not changed since I installed Rainbow CSV
<img width="1219" alt="スクリーンショット 2020-06-13 15 59 06" src="https://user-images.githubusercontent.com/28973144/84562744-d4c89600-ad91-11ea-85a2-9cf1bb37712e.png">

**Comment by mechatroner** [comment]
@sasshi-i Thank for bug report!
Do you still have the problem if you don't save the New file as "autodetection" and just immediately paste the CSV fragment into it?

What I think could be going on here is that Rainbow CSV uses a special "trick" for autodetection of copy-pasted CSV fragments - the extension puts a special single-use subscription which triggers on the first file edit, and when the first file edit is not CSV fragment copying, but something else (naming the file in your case) the single-use subscription gets disabled and Rainbow CSV never tries to run autodetection again for that file. So for example if you first copy the CSV fragment as step 1, and after that save the file as "autodetection2" - everything should work as expected. Please let me know if this is the case. I realize that this behavior is very odd, but it is possible to fix this.

**Comment by sasshi-i** [comment]
As you say, I copy my file to create another file, and I found autodetection is worked.
<img width="572" alt="スクリーンショット 2020-06-14 18 28 41" src="https://user-images.githubusercontent.com/28973144/84589890-e763cd80-ae6c-11ea-999e-8fe28d3a3732.png">

Alternatively It seems that reopening VS code also enabled autodetection.

Thank you!
