### ISSUE TITLE
Publish extensions to open-vsx

### ISSUE THREAD

**Issue by orblazer** [mechatroner/vscode_rainbow_csv#63]
I'm a [VS Codium](https://github.com/VSCodium/vscodium) user, a FLOSS version of VS Code, it's the same code but without the Microsoft's telemetry and branding.
I want to request if possible to add the _Rainbow CSV_ extension on the [open-vsx.org](https://open-vsx.org/) market to us doesn't need to works with the Microsoft marketplace as is unclear if it's legal to use it on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).

Additional info:

- This is [how to](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) publish a new extension.

**Comment by mechatroner** [comment]
Hi @orblazer,
If you or someone else is willing to publish Rainbow CSV to open-vsx.org, I absolutely authorize them to do it.

**Comment by k-gettingold** [comment]
@mechatroner I love this extension and want to use it in vscodium. I can set it up.

**Comment by mechatroner** [comment]
Thank you, @kl1900 . After you comment I decided to do another round of research regarding open-vsx and quickly discovered that there is an easy way to publish an extension to open-vsx with zero set up - it is much easier than the method which was suggested by @orblazer . Basically, I just sent a pull request to the official open-vsx repository (see the linked commit) which will handle all the complex steps and account management for us, or at least I hope it will work that way. Thank you for your readiness to maintain the open-vsx version, but it appears that we just can rely on the automatic publishing pipeline.

**Comment by mechatroner** [comment]
So I just did it! The extension is published and ready to use: https://open-vsx.org/extension/mechatroner/rainbow-csv 
I even installed VSCodium and checked the extension with it - seems to be working fine. @kl1900, please let me know if you find any problems with it.

**Comment by kl1900** [comment]
I got the extension in VSCodium, thank you!
