### ISSUE TITLE
"Too small to preview: Showing the original file instead" is confusing

### ISSUE THREAD

**Issue by yilmazdurmaz** [mechatroner/vscode_rainbow_csv#64]
hi there, nice work.

this message is so confusing that I even thought it was a message belonging to another extension. I even opened an issue there: https://github.com/jjuback/gc-excelviewer/issues/132

why confused? because the "preview" word is mostly used for compiled versions of a code such as html or markdown, I didn't suspect you had other practical meanings in mind. Add to that the message is too short to deduce otherwise if Rainbow CSV is not the only csv extension installed.

anyways, here is a suggestion. this message might be changed to reflect a bit more detail on what it does such as: "The file is not big thus showing the full file instead. Use this preview for files larger than 1MB"

cheers

**Comment by mechatroner** [comment]
Thank you for the feedback!

I will change the warning message in the next release.

**Comment by mechatroner** [comment]
Done
