### ISSUE TITLE
Won't it be best if "Edit csv", "Excel Viewer" and "Rainbow CSV" are merged (Keeping the best of each in one and adding extra features in a single extension)?

### ISSUE THREAD

**Issue by mesajidiqbal** [mechatroner/vscode_rainbow_csv#65]
https://marketplace.visualstudio.com/items?itemName=janisdd.vscode-edit-csv
https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer
https://marketplace.visualstudio.com/items?itemName=mechatroner.rainbow-csv

I tried "Data Preview" and "Data Set Preview" but I didn't find it as user friendly as "Edit CSV" and as pretty to eye as "Excel viewer" and "Rainbow CSV".
So, I thought of something like this:
    - Assume the new extension name is "Data Viewer" (An imaginary name which I thought)
    - The extension supports the flat-files (csv, tsv etc) and excel
    - Below is my thinking for the extension features and functionalities

- For flat-files (csv, tsv, txt etc)

1. When you click on a csv file it opens up like shown in the image "csv_data_view.png" (With values in different colors) ("rainbow csv" has already this feature)
    - Some options available in command palette (as in image) (Some options are already in rainbow csv (not all) and some extra options (e.g markdown table etc)) (Some extra features of "rainbow csv" (sql like joins etc) can be removed)
    - An icon to view it in tabular form (Top right, near code-runner)
![csv_data_view](https://user-images.githubusercontent.com/44871521/86041282-10867f80-ba63-11ea-935c-3c3fe737ffef.png)

2. After clicking the table icon a tab similar to the image "csv_tabular_view.png" opens up with following functionalities:
    - Options to toggle header, total/last row, first/index col, last col (As can be seen in top-left bar)
    - Option to change delimiter and reload file (top-right)
    - Option to edit the file (top-right, after delimiter option)
    - Option to filter data (See the filter icons after column name)
![csv_tabular_view](https://user-images.githubusercontent.com/44871521/86041308-1b411480-ba63-11ea-977b-512c9475ba1e.png)

3. After clicking the edit file option a page similar to the image "csv_edit_view.png" opens up with below functionalities:
    - Options to add rows/columns
    - Option to delete column (As "edit csv" already gives a delete icon after column name)
    - Option to trim all the data values
    - Options to apply/save the changes
![csv_edit_view](https://user-images.githubusercontent.com/44871521/86041348-25fba980-ba63-11ea-8ef2-edaf38372d2d.png)

- For excel files (xls, xlsx)

1. When you click on an excel file it directly opens up the file in tabular form as in image "excel_tabular_view.png" with following functionalities:
    - Options to toggle header, total/last row, first/index col, last col (As can be seen in top-left bar) - similar to csv option
    - Option to filter data (See the filter icons after column name) - similar to csv option
    - Option to export the one/all sheet as csv (top-right)
    - Tab in bottom bar for all sheets and navigation icons ("Excel viewer" already has this feature)
![excel_tabular_view](https://user-images.githubusercontent.com/44871521/86041358-2b58f400-ba63-11ea-82d4-facc8006c718.png)

Note: Only sheets with text data should be supported to keep the extension light-weight (Sheets with image/graphs should not open)

**Comment by mechatroner** [comment]
Hi @mesajidiqbal ,
I think you can use all three extensions together to have access to all of their features. There definitely exists some overlapping of functionality between them, but I don't see this as a problem. 
I want Rainbow CSV to be focused on CSV files handling and I don't plan to add excel or markdown-related logic to it.

**Comment by RandomFractals** [comment]
just gonna drop this here since my extension was mentioned there too.

https://github.com/jjuback/gc-excelviewer/issues/133#issuecomment-689584008

I agree with @mechatroner it's good to have options and use them as needed.
