### ISSUE TITLE
different color for columns 10 and above

### ISSUE THREAD

**Issue by tekdj7** [mechatroner/vscode_rainbow_csv#66]
columns 1-9 come in different colors.  column 10 shows as white.  column 11+ continues to show as white.  

please update, so that columns 11+ continue get new colors.

**Comment by mechatroner** [comment]
Hi @tekdj7,
Thanks for the bug report!

I tried to open a file with multiple columns just in case and I can't reproduce this. For me, colors are looping after the 10th column.  
What is your VSCode version? Could you please upload a non-sensitive version of the file you are using and/or add a screenshot?

**Comment by mechatroner** [comment]
@tekdj7,
Could you please also list your extensions, I think this can be done with `code --list-extensions` and post the output here. Maybe there is some bad interference with another extension.

**Comment by tekdj7** [comment]
after more testing with 20+ columns. 
 - column1 (white), column 2-9 (different colors), column 10 (white)
 - column11 (white), column 12-19 (different colors), column 20 (white)
 - column 21(white), cycle repeats

first, can you make so sequential columns never have the same column.  
  - currently, column 10 and column 11 are both white.  
  - currently, column 20 and column 21 are both white.

secondly, even better, could you make it where you provide more colors, so the colors don't start looping every 10 columns.

**Comment by mechatroner** [comment]
Well, I am glad it's not a bug.
> first, can you make so sequential columns never have the same column.

I actually did it for the default dark VSCode color scheme. To highlight columns Rainbow CSV uses syntax files which do not have any colors hard-coded into them, instead, these [syntax files](https://github.com/mechatroner/vscode_rainbow_csv/tree/master/syntaxes) must refer to some well known "scope names". And the color scheme you are using converts them to actual colors. There is also a way to override the colors your color scheme provides just for Rainbow CSV, here is the instruction: https://github.com/mechatroner/vscode_rainbow_csv/blob/master/test/color_customization_example.md#colors-customization

> secondly, even better, could you make it where you provide more colors, so the colors don't start looping every 10 columns.

It's not possible without modifying VSCode itself. But I have plans to submit a patch, so I hope this would be possible in the future. 
BTW I think it would be hard to distinguish more than 10 colors anyway. So a practical approach could be combining colors and font styles e.g. 10 - 15 colors * 3 (italic + bold + underline) will give us 30 - 45 different color codes.

**Comment by joshmcorreia** [comment]
@mechatroner 
> It's not possible without modifying VSCode itself. But I have plans to submit a patch, so I hope this would be possible in the future. BTW I think it would be hard to distinguish more than 10 colors anyway. So a practical approach could be combining colors and font styles e.g. 10 - 15 colors * 3 (italic + bold + underline) will give us 30 - 45 different color codes.

Did you ever come up with a solution for having more than 10 colors? I'm dealing with CSVs with dozens of columns and it would be very useful :)
