### ISSUE TITLE
Rainbow colours - some columns italic

### ISSUE THREAD

**Issue by clarotech** [mechatroner/vscode_rainbow_csv#67]
The rainbow colouring is excellent - I have a query though as one of the columns as well as being in a colour it makes the separation character italic (a pipe in my case)

See attached image

![2020-07-29_09h47_19](https://user-images.githubusercontent.com/20049400/88778668-b4f20380-d180-11ea-83bd-51ccd9b15225.png)

**Comment by mechatroner** [comment]
Hi @clarotech,
Thanks for the feedback!
One way to fix this is to use customized colors (without italic keyword), see instructions here: https://github.com/mechatroner/vscode_rainbow_csv/blob/master/test/color_customization_example.md
You can actually only customize the column which is italicized by your current color scheme, e.g. if it's column 3 you need to customize only `"scope": "entity.name.function.rainbow3"`
Another option is for me to make separator highlighting optional as suggested in #31 but the current VSCode API doesn't support this.
