### ISSUE TITLE
RBQL seems to crash after first use

### ISSUE THREAD

**Issue by brainz80** [mechatroner/vscode_rainbow_csv#68]
I have multiple similar CSV:s open. After successfully opened one in RBQL. The next ones will fail 

![image](https://user-images.githubusercontent.com/1257591/89153218-265cf800-d56d-11ea-921d-75adcbdc44ea.png)

**Comment by mechatroner** [comment]
Thank you very much, @brainz80 !
I just published version 1.7.1 which should fix the problem.
