### ISSUE TITLE
Manual file type change doesn't seems to activate coloration

### ISSUE THREAD

**Issue by brunetton** [mechatroner/vscode_rainbow_csv#7]
Hi

> If your csv, semicolon-separated or tab-separated file doesn't have .csv or .tsv extension, you can manually enable highlighting by clicking on the current language label mark in the right bottom corner and then choosing "CSV", "TSV" or "CSV (semicolon)" depending on the file content, see this screenshot

This doesn't seems to work in VScode 1.22.2. 
When I rename the file with ".tsv" extension, the plugin loads and works great, but doesn't when manually set file type to TSV using the menu in the bottom bar.

**Comment by mechatroner** [comment]
Hi, thanks for bug report.
1. Did you try to restart the editor? 
2. What about manually changing language to xml, json or something else (non-csv) using the menu, does it activate coloration, or other file types also fail? 
3. Maybe this is a problem with one particular file, can you try with other random files, maybe even-non table files.

Meanwhile I will also try to install 1.22.2 to check this.

**Comment by brunetton** [comment]
Hi, in fact it seems to work now; maybe I had some Code instances that haven't been restarted, don't know.
Sorry for the time ! 

I have another little problem: I do not have columns titles; only id. Example :

    A, B
    1, 2
    1, 2
    1, 2

The tooltip shows `Col #1`, and not `Col #1, "A"`. I'd probably open another ticket for this.

![capture du 2018-04-18 16-33-05](https://user-images.githubusercontent.com/86322/38938681-71a57a3e-4326-11e8-97f5-1b3cb468ce43.png)


Thanks !

**Comment by mechatroner** [comment]
Glad it worked!
To show column titles Rainbow CSV has to correctly guess that the file has a header, and in case of your example this header detection algorithm fails for two reasons:
1. File is too small, it needs to be at least 11 lines
2. Titles are too short: at least one title name must begin with three letters.
