### ISSUE TITLE
How to comment a line 

### ISSUE THREAD

**Issue by bladeshark9** [mechatroner/vscode_rainbow_csv#70]
When I open a .csv file with a semicolon separator and I want that when a line begins with a character such as "#", that the whole line takes on another color.
I tried to insert:
"rainbow_csv.comment_prefix":"#" ,
In the json file in vs code and it doesn't work.
Where am I wrong?

**Comment by mechatroner** [comment]
Hi @bladeshark9,
As I mentioned in #14 there is no simple solution for highlighting the comment lines. VSCode has a"decoration" mechanism, but it is not the same as syntax highlighting and would provide poor UX (although it would be arguably better than the current situation when adding a comment prefix to the config file has no effect on syntax highlighting as you have noticed). If we can't find a better solution I will probably implement the "decoration" mechanism. I will post an update in #14.
