### ISSUE TITLE
Collapse CSV Columns

### ISSUE THREAD

**Issue by lukepighetti** [mechatroner/vscode_rainbow_csv#76]
Requesting a command that collapses CSV Columns after running `Align CSV Columns`. 

It seems that in practice this would remove all trailing spaces from each cell.

**Comment by mechatroner** [comment]
Hi @lukepighetti,
We already have "Shrink CSV table: Remove leading and trailing whitespaces from all fields" command. Did you just overlook it or you suggesting something different?

**Comment by lukepighetti** [comment]
Does that work with TSV?

**Comment by mechatroner** [comment]
Yes, it just calls [trim()](https://www.w3schools.com/jsref/jsref_trim_string.asp) for each field. But it doesn't remove empty lines
