### ISSUE TITLE
Columns labels are not displayed 

### ISSUE THREAD

**Issue by brunetton** [mechatroner/vscode_rainbow_csv#8]
Hi,

I'm using Rainbow CSV on VScode v1.22.2 on a big TSV file that you can [download here](http://www.imf.org/external/pubs/ft/weo/2018/01/weodata/WEOApr2018alla.xls) (and change the grammar to TSV in VScode). 
Columns names are not displayed, only columns ids are:

![capture du 2018-04-23 11-29-12](https://user-images.githubusercontent.com/86322/39118971-066fd584-46eb-11e8-9767-c4d85b4c8205.png)

I don't think the problem come from this particular file as creating a little CSV test file make the same result: 

    long_label1, long_label2, long_label3
    data 1, data 2, data 3
    data 1, data 2, data 3
    data 1, data 2, data 3
    data 1, data 2, data 3
    data 1, data 2, data 3
    data 1, data 2, data 3
    data 1, data 2, data 3
    ... [120 lines more] 

![capture du 2018-04-23 11-40-56](https://user-images.githubusercontent.com/86322/39119159-773531a6-46eb-11e8-9e4e-28bf0bd55966.png)

Can you reproduce this ? (I tried deactivating all extensions but this one)

Thanks

**Comment by mechatroner** [comment]
Some CSV files have headers the others do not. 
We want to show column names only when the current CSV file has a header.
To find out whether CSV file has a header or not, "Rainbow CSV" uses header autodetection algorithm, which has failed in your case.

So there are two ways to fix this problem.
1. Improve header detection algorithm, currently it uses a primitive heuristic, which can be generalized.
2. No mater how good is our header-detection heuristic, header detection will still fail at some files, e.g. at this one:
```
fruit,color
apple,red
apple,green
strawberry,red
grapefruit,orange
banana,yellow
```
So In the next rainbow CSV release I will include the following two features:
a. Manual header enable/disable for the current file
b. Config rule how to handle headers in new files: 
always consider first line as header | never consider first line as header | use autodetection algorithm (default)

**Comment by brunetton** [comment]
> To find out whether CSV file has a header or not, "Rainbow CSV" uses header autodetection algorithm, which has failed in your case.

Indeed ! What a strange idea you got ;) I'd not have bet 1€ on such a behavior ! This should be documented, at least.
This "autodetection" has failed in ALL cases I encountered since I'm working with international statistical providers, I never seen this precious information of header columns names.
(by the way I don't remember having seen in my entire life any CSV file without header; and even if I'm working on a headerless file, I don't mind seeing the first value of current column, I can just ignore this info and look to the column id)

> So In the next rainbow CSV release I will include the following two features:
> a. Manual header enable/disable for the current file
> b. Config rule how to handle headers in new files:
> always consider first line as header | never consider first line as header | use autodetection algorithm (default)

And: **document it** ;)

And yes all automatic detections in computer science must be deactivate. [KISS](https://en.wikipedia.org/wiki/KISS_principle) ! 

Can't wait to have those options to definitely deactivate this algo and have my columns names ! This would be a HUDGE improvement for my everyday work.

Thanks

**Comment by waldyrious** [comment]
> b. Config rule how to handle headers in new files:
always consider first line as header | never consider first line as header | use autodetection algorithm (default)

It would also be nice to allow enabling headers in semi-tabular files (e.g. a table within a text file). For example, the first line of a table (say, after a blank line) could be toggled as that table's headers.

**Comment by waldyrious** [comment]
Exactly like that :)

**Comment by mechatroner** [comment]
> What a strange idea you got ;) I'd not have bet 1€ on such a behavior !
OK, I've removed the auto-detection code, the extension will always consider the first row as a header. The new behavior is easier to understand and doesn't create an impression that the software is buggy.
Also it works better with column names customization feature that will be useful for semi-tabular files (see example above) and other cases.  
I will publish this soon.

**Comment by brunetton** [comment]
Thanks @mechatroner :

**Comment by mechatroner** [comment]
I've published the new version. Thanks for feedback, guys! If you have more related or unrelated ideas, you are most welcome to share!

**Comment by brunetton** [comment]
Thanks ! Tested, and works well :) :+1:
