### ISSUE TITLE
File Association in combination with the use of Edit CSV does not work

### ISSUE THREAD

**Issue by acambule** [mechatroner/vscode_rainbow_csv#82]
Hi there, 

i have csv files that are formatted like this:
- First Line: Header
- Separator: Semicolon (;)
- Quote: Double Quotes ("Value")

So a file looks like this:
"Header1";"Header2";"Header3"
"Value1";"Value2";"Value3"

The File extensions is **.keys**
So i need to set the file-association in vs-code.

Now the problem is, that Edit CSV uses the builtin **CSV** Association to work.
But Rainbow adds more Associations, and to work with my files i need to change the association to **CSV (colon)** otherwise i do not get any Syntax Highlighting.

Is it possible to achieve both, could you change something to the behaviour, so that i can use both extensions together?
Here https://github.com/mechatroner/vscode_rainbow_csv/issues/65 you all stated we could use the extensions together instead of developing a big one, i agree, but they also need to fit together. 

Thanks and regards
Antonio

**Comment by mechatroner** [comment]
Hi @acambule,
You should be able to use "csv (semicolon)" dialect after the next release of Edit CSV - see the linked issue.
