### ISSUE TITLE
Open VSX Listing: Signing the Publisher Agreement

### ISSUE THREAD

**Issue by spoenemann** [mechatroner/vscode_rainbow_csv#83]
Thank you for being part of the Open VSX community by adding your extensions to the Open VSX Registry. Please note that the service was recently transferred to the Eclipse Foundation and urgent action on your part is needed so we can continue to list your extensions. To ensure uninterrupted service, please sign the [Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf) **on or before January 8, 2021**. If not signed by that date, your extensions will be delisted and will no longer appear on the site nor be available via the API. If you sign at a later date, your extensions will then be re-activated. The signing process is [explained in the Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) (steps 1 and 2).

Please also note that all extensions MUST have a license in order to be listed.

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

Today, there’s growing momentum around open source tools and technologies that support Visual Studio (VS) Code extensions. Leading global organizations are adopting these tools and technologies. This momentum has spurred demand for a marketplace without restrictions and limitations. Thanks for joining us on this journey as we continue to build the Open VSX community. We look forward to continued innovation from you in 2021!

**Comment by mechatroner** [comment]
Hi @spoenemann,
Thanks for the heads up!

I signed the agreement.

**Comment by spoenemann** [comment]
Hi @mechatroner, thanks for responding! I see you have an eclipse.org account, but the Publisher Agreement is not active yet. Have you completed step 2 of the publishing guide?
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by mechatroner** [comment]
Thanks, @spoenemann! I followed the instruction again and this time I ended up in a different UI and signed the agreement (again?).  Not sure what I did wrong the first time, maybe there were two agreements? Please let me know if it didn't work this time too.

**Comment by spoenemann** [comment]
All is good now :+1:

Could it be that the first time you signed the _Eclipse Contributor Agreement_? That is a different agreement used for contributing to source code of Eclipse open-source projects.
