### ISSUE TITLE
Support for "toggle line comment" command

### ISSUE THREAD

**Issue by jolsen71** [mechatroner/vscode_rainbow_csv#84]
I am working with CSV files that use the typical `#` prefix to indicate commented lines, and this is working great in Rainbow CSV. It would be really nice if the VS Code "toggle line comment" command would either add or remove a `#` from the current line or selected lines, just like VS Code can do when editing most programming languages.

I'm not a VS Code developer, but from what I've tried to research maybe it could be as simple as adding a few lines to `contributes.languages` section in your `package.json` file.
https://code.visualstudio.com/api/language-extensions/language-configuration-guide
Notably maybe:
```json
  "comments": {
    "lineComment": "#",    
  },
```
Or if you get really fancy, then the toggle could use what the user has configured in `rainbow_csv.comment_prefix` but I'd be happy if a hard-coded `#` worked.

Thanks for a very nice extension!

**Comment by mechatroner** [comment]
Hello there, sorry for the late reply!
I really like your proposal and I would love to implement this, but unfortunately, VSCode currently doesn't support "dynamic comment" functionality. It is possible to associate `#` with csv [statically](https://code.visualstudio.com/api/language-extensions/language-configuration-guide) but this will not work for some CSV files where `#` is not treated as a special symbol. 

BTW I just published version 3.0.0 which highlights comment lines with special comment syntax.

**Comment by mechatroner** [comment]
I just realized that my comment was literally what you wrote in the original message, sorry! I also tested the configuration you suggested and it looks like the static comment prefix doesn't affect highlighting, VSCode seems to be using it only for comment toggling, so I will include this feature in the next release.

**Comment by mechatroner** [comment]
Actually, it might even be possible to make it work with dynamic comments through `setLanguageConfiguration` API function. I will investigate.

**Comment by mechatroner** [comment]
Implemented in 3.1.0
