### ISSUE TITLE
Looking for support for anaconda install

### ISSUE THREAD

**Issue by chuckf201** [mechatroner/vscode_rainbow_csv#89]
I'm running spyder 5.0.0 under conda 1.10.0 and looking for installation guidance.

**Comment by mechatroner** [comment]
I just checked spyder 5.0.0 and it looks like this IDE is not VSCode based and uses a completely different incompatible extension model. So it would require a separate extension build from the ground up. So unfortunately there is no way currently to extend spyder ide with Rainbow CSV.

**Comment by chuckf201** [comment]
conda update conda
conda install --all

It worked for me

**Comment by chuckf201** [comment]
OK . Thanks for you help. Saved me hours of troubleshooting.
